### ISSUE TITLE
Correct parameter value for SiardFromDb external lob folder?

### ISSUE THREAD

**Issue by solfeggietto** [sfa-siard/SiardCmd#1]
I cannot get SiardFromDb 2.1 to run with parameter set for external lob folder (-x=<external lob folder>).

I am running windows .bat batchfile successfully as show below for:
1. Help -h
2. Internal blob documents
3. Export metadata.xml only (-e=<export meta data>

But i cannot get external lob folder to run proper
4. External lob folder (-x=<external lob folder>)

##### relative #####
-x=doc  

INFO:   sun.java.command: ch.admin.bar.siard2.cmd.SiardFromDb -o -x=doc -j=jdbc:
mysql://localhost:3306/blob01 -u=blob01user -p=test -s=sifrdb2.1-mysql-to-blob01
-ext.siard

INFO:   SIARD file             : C:\_temp\sifrdb2.1-mysql-to-blob01-ext.siard
apr 16, 2018 8:05:53 PM ch.enterag.utils.logging.IndentLogger log
INFO:   External LOB folder    : file:///C:/_temp/doc/
apr 16, 2018 8:05:53 PM ch.enterag.utils.logging.IndentLogger log
INFO:
  java.io.IOException: LOB folder value cannot be set!

##### relative outside ? #####
-x=../doc

External LOB folder  C:\_temp\..\doc does not exist!
apr 16, 2018 8:11:08 PM ch.enterag.utils.logging.IndentLogger log
INFO: SiardFromDb 2.1.38 terminates.

INFO:   sun.java.command: ch.admin.bar.siard2.cmd.SiardFromDb -o -x=..\doc -j=jd
bc:mysql://localhost:3306/blob01 -u=blob01user -p=test -s=sifrdb2.1-mysql-to-blo
b01-ext.siard

External LOB folder  C:\_temp\..\doc does not exist!
apr 16, 2018 8:11:08 PM ch.enterag.utils.logging.IndentLogger log
INFO: SiardFromDb 2.1.38 terminates.

##### Fixed external folder #####
-x=C:/temp2/test/doc

INFO:   sun.java.command: ch.admin.bar.siard2.cmd.SiardFromDb -o -x=C:/_temp2/te
st/doc -j=jdbc:mysql://localhost:3306/blob01 -u=blob01user -p=test -s=sifrdb2.1-
test-ext.siard

INFO:   SIARD file             : C:\_temp2\test\sifrdb2.1-test-ext.siard
apr 16, 2018 10:01:25 PM ch.enterag.utils.logging.IndentLogger log
INFO:   External LOB folder    : file:///C:/_temp2/test/doc/
apr 16, 2018 10:01:25 PM ch.enterag.utils.logging.IndentLogger log
INFO:
  java.io.IOException: LOB folder value cannot be set!

Parameters
  JDBC URL               : jdbc:mysql://localhost:3306/blob01
  Database user          : blob01user
  Database password      : ***
  SIARD file             : C:\_temp2\test\sifrdb2.1-test-ext.siard
  External LOB folder    : file:///C:/_temp2/test/doc/

Connected to jdbc:mysql://localhost:3306/blob01
Meta Data
  Table: "blob01"."blobs"
  Table: "blob01"."departments"

##### Windows Batchfile #####

REM *** Help
REM java -cp C:\prog\siard_suite-2.1\lib\siardcmd.jar ch.admin.bar.siard2.cmd.SiardFromDb -h > SiardFromDb_help.txt

REM *** Export SIARD internal documents
REM java -cp C:\prog\siard_suite-2.1\lib\siardcmd.jar ch.admin.bar.siard2.cmd.SiardFromDb -j=jdbc:mysql://localhost:3306/blob01 -u=blob01user -p=test -s=sifrdb2.1-mysql-to-blob01-int.siard > SiardFromDb_int_log.txt

REM *** Export SIARD external documents
java -cp C:\prog\siard_suite-2.1\lib\siardcmd.jar ch.admin.bar.siard2.cmd.SiardFromDb -o -x=doc -j=jdbc:mysql://localhost:3306/blob01 -u=blob01user -p=test -s=sifrdb2.1-mysql-to-blob01-ext.siard  > SiardFromDb_xml_log.txt

REM *** Export XML
REM java -cp C:\prog\siard_suite-2.1\lib\siardcmd.jar ch.admin.bar.siard2.cmd.SiardFromDb  -j=jdbc:mysql://localhost:3306/blob01 -u=blob01user -p=test -e=sifrdb2.1-mysql-to-blob01-int.xml > SiardFromDb_ext_log.txt

**Comment by cytex-media-solutions** [comment]
Guten Tag

Besten Dank für Ihre Nachricht. Ich bin zurzeit abwesend und ab Montag, 23. April 2018 wieder im Büro. Meine E-Mails prüfe ich daher nur sporadisch. 

Ich danke Ihnen für Ihre Geduld.

Mit freundlichen Grüssen
Simon Jutz

Geschäftsleiter
Cytex Media Solutions GmbH
Köchlistrasse 2
8004 Zürich
Telefon: 044 500 24 23
E-Mail: simon.jutz@cytex.ch
https://www.cytex.ch

**Comment by HartwigThomas** [comment]
Please read the manual.
The -x option is for exporting metadata. To specify a folder for external LOBs, use the -e option.
If no imported meta data are specified, the largest LOB column is stored externally.
If more complex external storage conditions are desired, one must specify them in imported template meta data.
A description of the precise format with examples for specifying external lobFolders can be found in the documentation of the project SiardApi.

**Comment by solfeggietto** [comment]
The manual had the -x=<external LOB folder> instruction and that part had a bug.
This is fixed in the latest SiardFromDb 2.1.49 (SiardCmd).
And i presume also in the latest SIARD-Suite-2.1.66.zip (SuardGui).

The console command from Windows .bat batchfile below now work as espected with the -x parameter to save any LOB in the database table columns to the .siard external folder /doc

REM *** SIARD-Suite-2.1.66 SiardCmd external LOB
REM https://github.com/sfa-siard/SiardGui/releases

java -cp C:\prog\SIARD-Suite-2.1.66\siard_suite-2.1\lib\siardcmd.jar ch.admin.bar.siard2.cmd.SiardFromDb -x=doc -j=jdbc:mysql://localhost:3306/blob01 -u=blob01user -p=test -s=siardcmd-2.1.40-extlob.siard  > siardcmd-2.1.40_extlob_log.txt
