### ISSUE TITLE
Support export from H2 1.4

### ISSUE THREAD

**Issue by mortenee** [sfa-siard/SiardCmd#10]
After doing some more research on original issue "Export from H2-database fails" I found that the problem is essentially that SiardCmd can export from H2 version 1.3 but not the newer 1.4 version with extension mv.db. Are there any plans for supporting newer H2 databases?
See also last comment in original issue for log from my testing with additional information.

**Comment by HartwigThomas** [comment]
Thank you for the tests. I shall have a look at 1.4 in the new year. Meanwhile I send you season's greetings and wish you a happy new year.

**Comment by HartwigThomas** [comment]
Currently we have no "use case" for upgrading to H2 1.4. (=> It would not be tested in a real life use.) Do you have one?

**Comment by mortenee** [comment]
We ended up using iso-sql for metadata and tsv for data rather than siard. You may close this issue.
