### ISSUE TITLE
java.lang.IllegalArgumentException: Column Name does not exist in this table (MS Access DB)

### ISSUE THREAD

**Issue by marcwer** [sfa-siard/SiardCmd#11]
I'm trying to create a SIARD File with SiardCmd v 2.1.102 from a simple MS Access DB (MS Access 2010) containing just one small table and one query (see DB attached as a zip-file). I'm executing siardfromdb.sh with the following command:

`$ ./siardfromdb.sh -j=jdbc:access:/home/marcel/siard/db-test/simpleDB.accdb -u=Admin -p='' -s=/home/marcel/siard/db-test/simpleDB.siard`

As a result I'm getting the following error:
```
  Table: "Admin"."tbl_Namen"
  View: "Admin"."qry_Personen"
  java.lang.IllegalArgumentException: Column with name tbl_Namen.Nachname does not exist in this table (Db=simpleDB.accdb;Table=tbl_Namen)
```
I've tried Java 1.11 (Linux; openjdk 11.0.2) and Java 1.8 (Windows 7; jre 1.8.0_131).

Example-DB:
[simpleDB.zip](https://github.com/sfa-siard/SiardCmd/files/2786197/simpleDB.zip)

**Comment by HartwigThomas** [comment]
Thank you. I shall look into this issue.

**Comment by HartwigThomas** [comment]
This problem is fixed in the current release of JDBCAccess/SiardCMD (2.1.124)
