### ISSUE TITLE
java.sql.SQLException: Resultset after last line.

### ISSUE THREAD

**Issue by MichaelHerrmanns** [sfa-siard/SiardCmd#12]
For some tests I try to create a SIARD File with the lastest of branch dev/enter from oracle (12c). With version v.2.1.102 I cant connect to this database.
  
  My run configuration for the test was 
  
  -l=300 -q=300 -o -j=jdbc:oracle:thin:user/pw@server:port/db -u=user -p=pw -s=digas.siard
  
  On trying to read the routines from the db there was a problem.

`Routine: user.SELECTLIEFERANT
  Type: user."REF CURSOR"
  java.sql.SQLException: Resultset after last line.`

The source for the routine is here.

`create or replace PROCEDURE SelectLieferant(

    L_Firmennr IN VARCHAR2,
    l_lieferantennrVon IN VARCHAR2,
    l_lieferantennrBis IN VARCHAR2,
    p_cursor in out sys_refcursor

    )

    as

	BEGIN

	   open p_cursor for 
	   select FIRMENNR, LIEFERANTENNR, LIEFERANTENNAME, SKONTOKZ, ELEK_RECHST, LIEFSTATUS 
	   from T_Lieferanten 
	   where FirmenNr =  L_firmennr
		AND to_number(LIEFERANTENNR) >=l_lieferantennrVon
		AND to_number(LIEFERANTENNR) <=l_lieferantennrBis;

	END SelectLieferant;`

**Comment by HartwigThomas** [comment]
This problem is fixed in the new release 2.1.124

**Comment by MichaelHerrmanns** [comment]
For further test I use 2.1.127. I've got the same error.

**Comment by HartwigThomas** [comment]
Thank you for the code for the procedure creation. I shall try and reproduce the problem.
