### ISSUE TITLE
ArithmeticException with Oracle DB and NUMBER column without precision and scale

### ISSUE THREAD

**Issue by Miss-Simone** [sfa-siard/SiardCmd#13]
I faced this issue:
 
Database Oracle. 
One table has a column defined with type NUMBER (without specification of precision or scale)
 
When this column contains a value with digits after the decimal point (not an integer) Siard throws a java.lang.ArithmeticException.
 
Some debugging shows me that this rises in class
ch.admin.bar.siard2.cmd.PrimaryDataFromDb
 
in method
private void getRecord(ResultSet rs, Record record)
 
For some reason the values of this database column are mapped to java.sql.Types.BIGINT. The conversion from the BigDecimal value obtained from the ResultSet to BigInteger with toBigIntegerExact()
throws an ArithmeticException. It is possible that it happens because NUMBER has undefined precision and scale (null, null).

i used Siard Suite 2.1.127.
i cloned commit e75178934477644bed0bea8f70b55037482f4d1a to Debug and Test

**Comment by HartwigThomas** [comment]
Hi Simone,
I was able to reproduce and fix the problem.
Obviously it was overlooked, that NUMBER without precision and scale maps to something like FLOAT(160).
(If precision is not missing, then the missing scale is 0 and the whole thing correctly is mapped to BIGINT.)
I shall integrate the fix into the master branch and add a release. That should be available soon.

**Comment by HartwigThomas** [comment]
Fixed in release 2.1.172
