### ISSUE TITLE
javacheck-function in bash-scripts doesn't seem to work at all

### ISSUE THREAD

**Issue by BBATools** [sfa-siard/SiardCmd#3]
Ubuntu 16.04 install with both java PATH and JAVA_HOME sett correctly still gives 
"No valid java executable".

If I change this:
java=/usr/bin/java
javacheck
ok=$?

For this (works on debian-based systems):
java=$(update-alternatives --query java | grep 'Value: ' | grep -o '/.*/jre/bin/java')
ok=1

then it works.

**Comment by HartwigThomas** [comment]
I am not happy with the suggested change, because I have very many JAVA versions installed.
I just tested it on Ubuntu and it worked without problems.

Can you be more specific about where and how your JAVA is installed?

**Comment by BBATools** [comment]
It wasn't really a suggested change as much as a workaround I ended up using.
But the workaround working also shows to me that the function "javacheck" doesn't work correctly in all cases.

My java is here:   /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
(sudo apt install openjdk-8-jdk openjfx)

If I change the pertinent parts of the script for this it still doesn't work.
java=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
javacheck
ok=$?

java -version gives 
openjdk version "1.8.0_162"

Looking at the code of the function I know see that it is because I'm using openjdk from the repos rather then oracle Java (should be ok since the differences are tiny now compared to how it used to be).

Rewrote the function and this know works for me:

javacheck()
{
  ok=0
  version=`$java -version 2>&1`
  # must start with something like 'java version "1.7.0_23"' or openjdk version "1.8.0_162"
  start=${version%%\"*}
  if [ "$start" = "java version " ] || [ "$start" = "openjdk version " ]
  then
    version=${version#*\"}
    if [ "$version" \> "$minjavaversion" ];
    then
      ok=1
    fi  
  fi
  return $ok
} # javacheck

**Comment by BBATools** [comment]
Seems my code was mangled. New attempt:

`javacheck()
{
  ok=0
  version=`$java -version 2>&1`
  # must start with something like 'java version "1.7.0_23"' or openjdk version "1.8.0_162"
  start=${version%%\"*}
  if [ "$start" = "java version " ] || [ "$start" = "openjdk version " ]
  then
    version=${version#*\"}
    if [ "$version" \> "$minjavaversion" ];
    then
      ok=1
    fi  
  fi
  return $ok
} # javacheck`

**Comment by HartwigThomas** [comment]
Thank you for the diagnosis. It will be useful, when we open SIARD for OpenJDK.
Currently SIARD does not officially support OpenJDK.
The JavaFX parts are clearly not compatible yet.
Whoever wants to try OpenJDK will have to use your work-around.

**Comment by HartwigThomas** [comment]
Thank you for the feed back. Before we open SIARD for OpenJDK we shall want to run all the tests of all 13 sub projects. Also we probably would have to increase the minimum compatible version from 7 to 8.
