### ISSUE TITLE
Case-senstive column names in psql are not considered

### ISSUE THREAD

**Issue by jaketpr-b** [sfa-siard/SiardCmd#31]
When using case-sensitive column names in a Postgres database the builder for the select queries does not consider this possibility. I tried to import a database which uses case-sensitive names for the columns. For example, the Postgres interpreter would translate a column name like `CaseSenstive` to `casesenstive` because it is not referenced in double-quotation marks (e.g. `"CaseSenstive"`). 

According to the error trace and some searching, this occurs in the file `PrimaryDataTransfer.java` within the `openTable()` function between lines 58 and 75.

**Comment by sdbuehlmann** [comment]
Hi @jaketpr-b, thank you for your report. We will try to reproduce that and get back to you. Thanks for your patience.

**Comment by sdbuehlmann** [comment]
Hi @jaketpr-b, i can confirm that this is a bug; we've successfully reproduced it. But it's quite a funny one: It seems that the double-quotation marks are only missing if the column name is written only in capital letters. Is that also true in your case?

We will investigate further and then fix it. I will keep you updated.

**Comment by jaketpr-b** [comment]
Hi @sdbuehlmann, thanks for your quick response. Yeah, the table in question has the column name also written in capital letters. One example would be a column name like `FG_SK_1`

**Comment by sdbuehlmann** [comment]
Issue [SiardGui#53](https://github.com/sfa-siard/SiardGui/issues/53) is also caused by the same problem (missing double-quotation marks in the generated SQL statement when creating foreign-keys).

**Comment by jaketpr-b** [comment]
Hi @sdbuehlmann, has the issue been solved or are you still working on it?

**Comment by mburri** [comment]
@jaketpr-b 
No, the issue has not yet been resolved and did not make it into the January release.

**Comment by mburri** [comment]
Unfortunatly not. We will updated this issue if we are working on it.
