### ISSUE TITLE
Problem with cmd-line switches on Linux

### ISSUE THREAD

**Issue by BBATools** [sfa-siard/SiardCmd#4]
Tested same command on both windows and Liux. Works on Windows but not on Linux:

Command:
./siardfromdb.sh -x=siard_test -j=jdbc:sqlserver://10.0.2.2\SQLEXPRESS:1433 -u=bba -p=bba -s=siard_test/test.siard

This gives error:  -j=jdbc:sqlserver:/10.0.2.2SQLEXPRESS:1433 does not exist

It seems to have both stripped out one slash  and one backslash.

Tried with extra backslashes like this:
./siardfromdb.sh -x=siard_test -j=jdbc:sqlserver:\//10.0.2.2\\SQLEXPRESS:1433 -u=bba -p=bba -s=siard_test/test.siard

This fixes the missing backslash but I didn't find av combination of slashes/backslashes that fixed the missing slash after sqlserver:

**Comment by HartwigThomas** [comment]
There was a confusion of From and To in the scripts. That has been corrected in v2.1.49.

**Comment by BBATools** [comment]
This was not because of the to and from - that was only in the cmd-file, not the bash-script.
To be certain I tested again with version v2.1.49 with the exact same result as reported earlier.

This doesn't work:
./siardfromdb.sh -o -x="siard_test_lobs" -j="jdbc:sqlserver://10.0.2.2\SQLEXPRESS:1433" -u="bba" -p="bba" -s="siard_test/test.siard" 

But I know see that this works:
java -cp lib/siardcmd.jar ch.admin.bar.siard2.cmd.SiardFromDb -o -x="siard_test_lobs" -j="jdbc:sqlserver://10.0.2.2\SQLEXPRESS:1433" -u="bba" -p="bba" -s="siard_test/test.siard"

**Comment by HartwigThomas** [comment]
I'll check it. (Actually both, a bash script as well as a cmd script contained a confusion.)

**Comment by BBATools** [comment]
Thanks.

Since the second command worked I just successfully exported a database with blobs to external files with openjdk on Linux ☺


Morten Eek

Rådgiver
Bergen byarkiv | Avdeling for moderne arkiver
Postboks 7700  | 5020 Bergen kommune
Tlf:  93 63 06 81

www.bergen.kommune.no/byarkivet<https://www.bergen.kommune.no/omkommunen/avdelinger/bergen-byarkiv>


Bergen kommune er forpliktet til å behandle alle dokumenter, også e-post, i samsvar med bestemmelsene i offentlighetsloven og arkivlovgivning. Det betyr at inngående og utgående e-post kan bli gjenstand for offentlig innsyn dersom det er saksrelatert eller har verdi som dokumentasjon.

Fra: Hartwig Thomas [mailto:notifications@github.com]
Sendt: 23. april 2018 15:09
Til: sfa-siard/SiardCmd
Kopi: Eek, Morten; Author
Emne: Re: [sfa-siard/SiardCmd] Problem with cmd-line switches on Linux (#4)


I'll check it. (Actually both, a bash script as well as a cmd script contained a confusion.)

**Comment by HartwigThomas** [comment]
I corrected the shell scripts. In SiardCmd v2.1.54 (and in SiardGui v2.1.68) it is sufficient to quote the SQL Server JDBC URL with duplicated backslashes:
-j="jdbc:sqlserver://10.0.2.2\\SQLEXPRESS:1433"
