### ISSUE TITLE
Missing line breaks in xml-files

### ISSUE THREAD

**Issue by BBATools** [sfa-siard/SiardCmd#6]
All xml-files seems to be missing line breaks so that you end up with a few very long lines when the files are opened in an editor. Tested on both windows and linux. XSD-files are fine.
This was not the case with earlier (pre 2.1) versions of siard suite.

**Comment by HartwigThomas** [comment]
All XML-handling tools make it very easy to view XML prettily formatted (e.g. Eclipse, Crimson Editor, XML Notepad, ...). Different people tend to have different ideas, what is pretty.
Also putting line breaks gets us into trouble between the LF- and the CRLF fraction.
Any users that want to handle the XML are likely to have suitable tools for that.
Formally the XML files are correct. That is all, which is important to us.
Which XML file did you attempt to open in an Editor and for which purpose?

**Comment by HartwigThomas** [comment]
Generally I'd be interested in cases, where the Oracle Upload fails.
Manual changes should not (or very rarely) be neccessary.
If there are reasonable changes you can perform manually, they can also be performed by SIARD Suite.

It is true, that we invested more effort in supporting download of (almost) every database.
But uploads from correct SIARD files should not fail (except maybe for enabling constraints, which we consider not really a failure).
