### ISSUE TITLE
SiardCmd import xml and lob folder parameters

### ISSUE THREAD

**Issue by solfeggietto** [sfa-siard/SiardCmd#8]
Can you provide a reference guide with examples of the usage of the following parameters:
-i=<import metadata>
-x=<external lob folder>

It is troublesome to use SiardCmd with those 2 parameters without a better understanding on how the parameters are configured, as well as the imported metadata.xml and how this make an impact on the extracted siard-file. As it is i cannot figure out how to get them to produce external lob folders like i want them to be. PS writing {element} because < and > are formatted html here.

import metadata:
> one can add {description} element at any SIARD 2.1 metadata element according to spec?
> one can add {lobFolder} at Database and Column level?
> one can specify parts of the whole schema<n> and table<n> etc? 
   and if so, will SiardCmd add any missing parts or do one need exact match of imported
   metadata.xml with the imported database structure?

external lob folder
> Do SiardCmd support any combination of Database and Colum level lobFolder element with file= attribute for the LOB file?
> if import metadata parameter is in use and with {lobFolder} pointing outside the SIARD-file:
   do one need the -x parameter added as well and if so just blank as imported metadata will target it?
> Default Enternal LOB reference is fixed (not relative) when using SiardCmd -x=documents
   {lobFolder}file:///Y:/uttrekk-SiardFromDb-2.1/b20/demo/sifrdb2.1.68-mysql-to-blob01ext/report/../documents/{/lobFolder}
> What other lobFolder element and file= attribute PATH + FILE syntaxes do SiardCmd support?
   For interoperability reasons it will be good to have them listed in the documentation of SiardCmd

Also note that the parameter listing in the SiardGui (which holds SiardCmd as well) is inacurate, as some parts are listed as [-i <import metadata>] this missing the = though i have not tested if a Space and a = both are working).

**Comment by HartwigThomas** [comment]
The documentation of the most recent release (2.1.96) contains an example how to work with external LOBs.
The documentation of the command-line arguments will be improved.
