### ISSUE TITLE
SiardCmd versioning mismatch?

### ISSUE THREAD

**Issue by solfeggietto** [sfa-siard/SiardCmd#9]
The current latest release of SiardCmd identifies it at the GitHub here as 2.1.58: JAVA 10. However downloading and unzipping the released file that name itself siardcmd-2.1.96.zip, then running this version confirms itself as being version 2.1.96.

How come the release number is 2.1.58 while the running one is 2.1.96?

**Comment by HartwigThomas** [comment]
Thank you for the comment. The wrong title of the release has been corrected.
